version: '3.8'
services:
  api:
    build: ./api
    container_name: api
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: wikidata
      DB_USER: postgres
      DB_PASSWORD: learnfullstack
    depends_on:
      - db
  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: learnfullstack
      POSTGRES_DB: wikidata
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: